# Generated by Django 2.2.24 on 2021-08-26 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('Jurusan', models.CharField(choices=[('TMPO', 'TMPO'), ('SIJA', 'SIJA'), ('TFLM', 'TFLM'), ('TEDK', 'TEDK'), ('KGSP', 'KGSP'), ('TTL', 'TTL')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Kelas', models.CharField(choices=[('XII SIJA 2', 'XII SIJA 2'), ('XII TFLM 1', 'XII TFLM 1'), ('XII SIJA 1', 'XII SIJA 1'), ('XII TMPO 2', 'XII TMPO 2'), ('XII TTL 1', 'XII TTL 1'), ('XII KGSP 2', 'XII KGSP 2'), ('XII TFLM 2', 'XII TFLM 2'), ('XII TTL 2', 'XII TTL 2'), ('XII KGPS 1', 'XII KGSP 1'), ('XII TEDK 1', 'XII TEDK 1'), ('XII TEDK 2', 'XII TEDK 2'), ('XII TMPO 1', 'XII TMPO 1')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('NISN', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Nama', models.CharField(max_length=100)),
                ('Jenis_Kelamin', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=10)),
                ('Alamat', models.CharField(max_length=50, null=True)),
                ('id_kelas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('id_jurusan', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('absenIn', models.DateTimeField(auto_now_add=True)),
                ('absenOut', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
