# Generated by Django 2.2.24 on 2021-08-26 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectAbsen', '0002_auto_20210826_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='Jurusan',
            field=models.CharField(choices=[('TTL', 'TTL'), ('TMPO', 'TMPO'), ('KGSP', 'KGSP'), ('TFLM', 'TFLM'), ('SIJA', 'SIJA'), ('TEDK', 'TEDK')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='Kelas',
            field=models.CharField(choices=[('XII SIJA 1', 'XII SIJA 1'), ('XII SIJA 2', 'XII SIJA 2'), ('XII TFLM 2', 'XII TFLM 2'), ('XII TEDK 1', 'XII TEDK 1'), ('XII TTL 2', 'XII TTL 2'), ('XII KGSP 2', 'XII KGSP 2'), ('XII TMPO 2', 'XII TMPO 2'), ('XII TFLM 1', 'XII TFLM 1'), ('XII TEDK 2', 'XII TEDK 2'), ('XII KGPS 1', 'XII KGSP 1'), ('XII TMPO 1', 'XII TMPO 1'), ('XII TTL 1', 'XII TTL 1')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='absenIn',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 26, 7, 12, 0, 98860, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='absenOut',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 26, 7, 12, 0, 98860, tzinfo=utc)),
        ),
    ]
