# Generated by Django 2.2.24 on 2021-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectAbsen', '0011_auto_20210826_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='Jurusan',
            field=models.CharField(choices=[('TMPO', 'TMPO'), ('TEDK', 'TEDK'), ('TTL', 'TTL'), ('SIJA', 'SIJA'), ('TFLM', 'TFLM'), ('KGSP', 'KGSP')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='Kelas',
            field=models.CharField(choices=[('XII TTL 2', 'XII TTL 2'), ('XII SIJA 1', 'XII SIJA 1'), ('XII TEDK 1', 'XII TEDK 1'), ('XII TMPO 2', 'XII TMPO 2'), ('XII TTL 1', 'XII TTL 1'), ('XII SIJA 2', 'XII SIJA 2'), ('XII TFLM 1', 'XII TFLM 1'), ('XII TFLM 2', 'XII TFLM 2'), ('XII KGSP 2', 'XII KGSP 2'), ('XII TMPO 1', 'XII TMPO 1'), ('XII KGPS 1', 'XII KGSP 1'), ('XII TEDK 2', 'XII TEDK 2')], max_length=10, null=True),
        ),
    ]
